class CfgLoadouts {
  #include "KITS\GEAR\common.hpp"

  class UNIFORMS {

    #include "KITS\UNIFORMS\RHS_UNI_NATO_GER_BUNDESWEHR_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_NATO_GREEKFORCES_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_NATO_UKRAINIAN_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_NATO_US_ARMY_2020.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_NATO_US_MARINES_DESERT_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_NATO_US_MARINES_WOODLAND_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_NATO_US_NAVY_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_NATO_US_RANGERS_2020.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ANY_CROATIAN_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ANY_CZECHFORCES_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ANY_SERBIANFORCES_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ANY_YUGOSLAVIA_2000.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_RU_COSSACKS_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_RU_RATNIK_2020.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_RU_RATNIK_D_2020.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_RU_SPETSNAZ_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ID_MEC_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ID_NAVSOG_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ID_REBELS_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ID_INSURGENTS_2000.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_NATO_NL_DUTCH_ARMY_2000.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ID_IRAQI_ARMY_2000.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ID_TRIBAL_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ID_TURKISH_ARMY_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_NATO_US_ARMY_1980.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_RU_ARMY_1980.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_NATO_DE_WESTGERMAN_1980.hpp"
    #include "KITS\UNIFORMS\APEX_UNI_ANY_AFRICAN_POLICE_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ID_AFRICAN_MILITIA_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_NATO_FRANCE_2010.hpp"



    #include "KITS\UNIFORMS\VN_UNI_NLF_Vietcong.hpp"
    #include "KITS\UNIFORMS\VN_UNI_PAVN_NVA.hpp"
    #include "KITS\UNIFORMS\VN_UNI_PAVN_NVA_Early.hpp"
    #include "KITS\UNIFORMS\VN_UNI_SVA_ARVN.hpp"
    #include "KITS\UNIFORMS\VN_UNI_US_MACV.hpp"
    #include "KITS\UNIFORMS\VN_UNI_US_SOG.hpp"


  };

  class GEAR {

    #include "KITS\GEAR\RHS_GEAR_NATO_BUNDESWEHR_2010_G36.hpp"
    #include "KITS\GEAR\RHS_GEAR_NATO_GREEKFORCES_2010_L1A1.hpp"
    #include "KITS\GEAR\RHS_GEAR_NATO_UKRAINIAN_2010_AK74UUK.hpp"
    #include "KITS\GEAR\RHS_GEAR_US_ARMY_2010_M16A4.hpp"
    #include "KITS\GEAR\RHS_GEAR_US_MARINES_2020_M27.hpp"
    #include "KITS\GEAR\RHS_GEAR_US_NAVY_2010_MK18.hpp"
    #include "KITS\GEAR\RHS_GEAR_US_RANGERS_2010_SCAR.hpp"
    #include "KITS\GEAR\RHS_GEAR_ANY_CROATIAN_2010_VHS.hpp"
    #include "KITS\GEAR\RHS_GEAR_ANY_CZECHFORCES_2010_VZ58.hpp"
    #include "KITS\GEAR\RHS_GEAR_ANY_SERBIAN_ARMY_2010_M21.hpp"
    #include "KITS\GEAR\RHS_GEAR_ANY_YUGOSLAVIA_2000_M70.hpp"
    #include "KITS\GEAR\RHS_GEAR_RU_ARMY_2010_AK74M.hpp"
    #include "KITS\GEAR\RHS_GEAR_ID_MEC_2010_AK103.hpp"
    #include "KITS\GEAR\RHS_GEAR_ID_REBELS_2010_AKMN.hpp"
    #include "KITS\GEAR\RHS_GEAR_ID_INSURGENTS_2000_AK74N.hpp"
    #include "KITS\GEAR\RHS_GEAR_ID_NAVSOG_2010_M16A4.hpp"
    #include "KITS\GEAR\RHS_GEAR_ID_IRAQI_ARMY_2000_AKMN.hpp"
    #include "KITS\GEAR\RHS_GEAR_NATO_DUTCH_ARMY_2000_M4.hpp"
    #include "KITS\GEAR\RHS_GEAR_RU_ARMY_1980_AK74.hpp"
    #include "KITS\GEAR\RHS_GEAR_US_ARMY_1980_M16A1.hpp"
    #include "KITS\GEAR\RHS_GEAR_ID_TURKISH_2010_HK33A2.hpp"
    #include "KITS\GEAR\RHS_GEAR_ID_TRIBAL_2010_AKMN.hpp"
    #include "KITS\GEAR\RHS_GEAR_NATO_WESTGERMAN_1980_G3.hpp"
    #include "KITS\GEAR\RHS_GEAR_ANY_AFRICAN_POLICE_2010_FAMAS.hpp"
    #include "KITS\GEAR\RHS_GEAR_ID_AFRICAN_MILITIA_2010_AKMN.hpp"
    #include "KITS\GEAR\RHS_GEAR_NATO_FRANCE_2010_FAMAS.hpp"

    #include "KITS\GEAR\VN_GEAR_NVA_VC1970.hpp"
    #include "KITS\GEAR\VN_GEAR_US_ARMY1970.hpp"
    #include "KITS\GEAR\VN_GEAR_US_SOG1970.hpp"
    #include "KITS\GEAR\VN_GEAR_NVA_VC1946.hpp"

  };
};
