class CfgLoadouts {
  #include "KITS\GEAR\common.hpp"

  class UNIFORMS {

    #include "KITS\UNIFORMS\RHS_UNI_CZ_CZECHFORCES_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_DE_BUNDESWEHR_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ID_MEC_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ID_NAVSOG_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_RU_RATNIK_2020.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_RU_RATNIK_D_2020.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_RU_SPETSNAZ_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_SERBIAN_ARMY_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_US_ARMY_2020.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_US_MARINES_DESERT_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_US_MARINES_WOODLAND_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_US_NAVY_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_US_RANGERS_2020.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_YUGOSLAVIA_ARMY_2000.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_UA_ARMY_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_ID_REBELS_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_DPR_COSSACKS_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_GR_GREEKFORCES_2010.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_CROATIAN_ARMY_2010.hpp"


    #include "KITS\UNIFORMS\RHS_UNI_SOV_ARMY_1980.hpp"
    #include "KITS\UNIFORMS\RHS_UNI_US_ARMY_1980.hpp"

    #include "KITS\UNIFORMS\VN_UNI_NLF_Vietcong.hpp"
    #include "KITS\UNIFORMS\VN_UNI_PAVN_NVA.hpp"
    #include "KITS\UNIFORMS\VN_UNI_SVA_ARVN.hpp"
    #include "KITS\UNIFORMS\VN_UNI_US_MACV.hpp"
    #include "KITS\UNIFORMS\VN_UNI_US_SOG.hpp"

  };

  class GEAR {

    #include "KITS\GEAR\RHS_GEAR_CZ_CZECHFORCES_2010_VHS.hpp"
    #include "KITS\GEAR\RHS_GEAR_DE_BUNDESWEHR_2010_G36.hpp"
    #include "KITS\GEAR\RHS_GEAR_ID_MEC_2010_AK103.hpp"
    #include "KITS\GEAR\RHS_GEAR_ID_NAVSOG_2010_M16A4.hpp"
    #include "KITS\GEAR\RHS_GEAR_RU_ARMY_2010_AK74M.hpp"
    #include "KITS\GEAR\RHS_GEAR_SERBIAN_ARMY_2010_M21.hpp"
    #include "KITS\GEAR\RHS_GEAR_US_ARMY_2010_M16A4.hpp"
    #include "KITS\GEAR\RHS_GEAR_US_NAVY_2010_MK18.hpp"
    #include "KITS\GEAR\RHS_GEAR_US_RANGERS_2010_SCAR.hpp"
    #include "KITS\GEAR\RHS_GEAR_HS_CROATIAN_2010_VHS.hpp"
    #include "KITS\GEAR\RHS_GEAR_GR_GREEKFORCES_2010_L1A1.hpp"
    #include "KITS\GEAR\RHS_GEAR_ID_REBELS_2010_AKMN.hpp"
    #include "KITS\GEAR\RHS_GEAR_UA_UKRAINIAN_2010_AK74UUK.hpp"
    #include "KITS\GEAR\RHS_GEAR_US_MARINES_2020_M27.hpp"
    #include "KITS\GEAR\RHS_GEAR_YUGOSLAVIA_ARMY_2000_M70.hpp"

    #include "KITS\GEAR\RHS_GEAR_SOV_ARMY_1980_AK74.hpp"
    #include "KITS\GEAR\RHS_GEAR_US_ARMY_1980_M14.hpp"

    #include "KITS\GEAR\VN_GEAR_NVA_VC1970.hpp"
    #include "KITS\GEAR\VN_GEAR_US_ARMY1970.hpp"
    #include "KITS\GEAR\VN_GEAR_US_SOG1970.hpp"

  };
};
