//Roles
ROLE_CIV = 100;
ROLE_SPECTATOR = 99;

ROLE_PL = 0; //Platoon leader
ROLE_CLS = 1; //Medic
ROLE_SL = 2; //Squad leader
ROLE_TL = 3; //Team leader
ROLE_AR = 4; //Automatic rifleman
ROLE_AAR = 5; //Assistant automatic rifleman
ROLE_RAT = 6; //Rifleman (light anti-tank)
ROLE_CE = 7; //Combat engineer
ROLE_R = 8; //Rifleman
ROLE_MG = 9; //Machinegunner
ROLE_AM = 10; //Ammo man - for MG
ROLE_MGTL = 11; //Machinegun team lead
ROLE_AT = 12; //Anti-tank
ROLE_AAT = 13; //Assistant anti-tank
ROLE_P = 14; //Pilot
ROLE_CR = 15; //Crewman
ROLE_MK = 16; //Marksman

UNIT_SPECTATOR = "VirtualMan_F";

UNIT_OPFOR_PL = "O_officer_F";
UNIT_OPFOR_CLS = "O_medic_F";
UNIT_OPFOR_SL = "O_Soldier_SL_F";
UNIT_OPFOR_TL = "O_Soldier_TL_F";
UNIT_OPFOR_AR = "O_Soldier_AR_F";
UNIT_OPFOR_AAR = "O_Soldier_A_F";
UNIT_OPFOR_RAT = "O_Soldier_LAT_F";
UNIT_OPFOR_CE = "O_soldier_exp_F";
UNIT_OPFOR_R = "O_Soldier_F";
UNIT_OPFOR_MG = "O_HeavyGunner_F";
UNIT_OPFOR_AM = "O_Soldier_unarmed_F";
UNIT_OPFOR_MGTL = "O_soldier_PG_F";
UNIT_OPFOR_AT = "O_Soldier_AT_F";
UNIT_OPFOR_AAT = "O_Soldier_AAT_F";
UNIT_OPFOR_P = "O_pilot_F";
UNIT_OPFOR_CR = "O_crew_f";
UNIT_OPFOR_MK = "O_soldier_M_F";
UNIT_OPFOR_SP = "O_Sharpshooter_F";

UNIT_BLUFOR_PL = "B_officer_F";
UNIT_BLUFOR_CLS = "B_medic_F";
UNIT_BLUFOR_SL = "B_Soldier_SL_F";
UNIT_BLUFOR_TL = "B_Soldier_TL_F";
UNIT_BLUFOR_AR = "B_soldier_AR_F";
UNIT_BLUFOR_AAR = "B_soldier_AAR_F";
UNIT_BLUFOR_RAT = "B_soldier_LAT_F";
UNIT_BLUFOR_CE = "B_soldier_exp_F";
UNIT_BLUFOR_R = "B_Soldier_F";
UNIT_BLUFOR_MG = "B_HeavyGunner_F";
UNIT_BLUFOR_AM = "B_Soldier_unarmed_F";
UNIT_BLUFOR_MGTL = "B_soldier_PG_F";
UNIT_BLUFOR_AT = "B_Soldier_AT_F";
UNIT_BLUFOR_AAT = "B_Soldier_AAT_F";
UNIT_BLUFOR_P = "B_pilot_F";
UNIT_BLUFOR_CR = "B_crew_F";
UNIT_BLUFOR_MK = "B_soldier_M_F";
UNIT_BLUFOR_SP = "B_RangeMaster_F";

UNIT_INDFOR_PL = "I_officer_F";
UNIT_INDFOR_CLS = "I_medic_F";
UNIT_INDFOR_SL = "I_Soldier_SL_F";
UNIT_INDFOR_TL = "I_Soldier_TL_F";
UNIT_INDFOR_AR = "I_Soldier_AR_F";
UNIT_INDFOR_AAR = "I_Soldier_AAR_F";
UNIT_INDFOR_RAT = "I_Soldier_LAT_F";
UNIT_INDFOR_CE = "I_Soldier_exp_F";
UNIT_INDFOR_R = "I_soldier_F";
UNIT_INDFOR_MG = "I_support_MG_F";
UNIT_INDFOR_AM = "I_Soldier_A_F";
UNIT_INDFOR_MGTL = "I_Soldier_lite_F";
UNIT_INDFOR_AT = "I_Soldier_AT_F";
UNIT_INDFOR_AAT = "I_Soldier_AAT_F";
UNIT_INDFOR_P = "I_pilot_F";
UNIT_INDFOR_CR = "I_crew_F";
UNIT_INDFOR_MK = "I_Soldier_M_F";
UNIT_INDFOR_SP = "I_Survivor_F";

UNIT_CIV_R = "C_man_1";
