#define UNIFORM_MARPAT_WD 0
#define UNIFORM_MARPAT_D 1
#define UNIFORM_G3_BLACK 5
#define UNIFORM_TTSKO_FOREST 2
#define UNIFORM_EMR_DESERT 3
#define UNIFORM_EMR_SUMMER 4
#define UNIFORM_SPECTER_S_FLORA 6
#define UNIFORM_COLDWAR_ERA_1 7
#define UNIFORM_M88_MOUNTAIN_LES 8
#define UNIFORM_M93_OAKLEAF 9
#define UNIFORM_CSAT_HEX 10
#define UNIFORM_CSAT_URBAN 11
#define UNIFORM_M93_FLECKTARN 12
#define UNIFORM_M93_WOODLAND 13
#define UNIFORM_AAF 14
#define UNIFORM_GUERILLA 15
#define UNIFORM_WETSUIT 16
#define UNIFORM_CIVILIAN_TANOA 17
#define UNIFORM_CIVILIAN 18

#define ATTACHMENTS_NONE ""
#define ATTACHMENTS_BLUFOR_FLASHLIGHT "rhsusf_acc_M952V"
#define ATTACHMENTS_OPFOR_FLASHLIGHT "rhs_acc_2dpZenit"

#define ATTACHMENT_VALUES {\
ATTACHMENTS_NONE,\
ATTACHMENTS_BLUFOR_FLASHLIGHT,\
ATTACHMENTS_OPFOR_FLASHLIGHT}

#define ATTACHMENT_TEXTS {\
"No Attachments",\
"BLUFOR Flashlight (M16/M4/HK/G36)",\
"OPFOR Flashlight (AK74/AKM)"}

#define UNIFORM_VALUES {\
UNIFORM_MARPAT_WD,\
UNIFORM_MARPAT_D,\
UNIFORM_G3_BLACK,\
UNIFORM_TTSKO_FOREST,\
UNIFORM_EMR_DESERT,\
UNIFORM_EMR_SUMMER,\
UNIFORM_SPECTER_S_FLORA,\
UNIFORM_COLDWAR_ERA_1,\
UNIFORM_M88_MOUNTAIN_LES,\
UNIFORM_M93_OAKLEAF,\
UNIFORM_CSAT_HEX,\
UNIFORM_CSAT_URBAN,\
UNIFORM_M93_FLECKTARN,\
UNIFORM_M93_WOODLAND,\
UNIFORM_AAF,\
UNIFORM_GUERILLA,\
UNIFORM_WETSUIT,\
UNIFORM_CIVILIAN_TANOA,\
UNIFORM_CIVILIAN}

#define UNIFORM_TEXTS {\
"B MARPAT WD*",\
"B MARPAT D*",\
"B G3 Black~",\
"O TTsKO Forest~",\
"O EMR Desert*",\
"O EMR Summer*",\
"I Specter-S Flora~",\
"I Cold War Era 1~",\
"O M88 Mountain Les*",\
"O M93 Oakleaf~",\
"O CSAT Hex",\
"O CAST Urban",\
"I M93 Flecktarn~",\
"I M93 Woodland~",\
"I AAF",\
"I Guerilla~",\
"B Wetsuit~",\
"C Civilian (Tanoa)",\
"C Civilian"}

#define WEAPONS_M4A1_BLOCK_M249_M240G_M136_GUST 0
#define WEAPONS_AK74M_PKM_PKP_RPG7_RPG32 1
#define WEAPONS_M16A4_M249_M240G_M136_GUST 2
#define WEAPONS_SCARH_MK18320_SAW_M240_M136_GUST 3
#define WEAPONS_MX_STONER_MXSW_RPG32_TITAN 4
#define WEAPONS_KATIBA_ZAFIR_LYNX_RPG32_TITAN 5
#define WEAPONS_KAR98K_PKM_MG42_RPG26_RPG7 6
#define WEAPONS_UNARMED 7

#define WEAPON_VALUES {\
WEAPONS_M4A1_BLOCK_M249_M240G_M136_GUST,\
WEAPONS_AK74M_PKM_PKP_RPG7_RPG32,\
WEAPONS_M16A4_M249_M240G_M136_GUST,\
WEAPONS_SCARH_MK18320_SAW_M240_M136_GUST,\
WEAPONS_MX_STONER_MXSW_RPG32_TITAN,\
WEAPONS_KATIBA_ZAFIR_LYNX_RPG32_TITAN,\
WEAPONS_KAR98K_PKM_MG42_RPG26_RPG7,\
WEAPONS_UNARMED}

#define WEAPON_TEXTS {\
"B M4A1 Block II, M249, M240G, M136 / GUST",\
"O AK74M, PKM, PKP, RPG7 / RPG-32",\
"B M16A4, M249, M240G, M136 / GUST",\
"B SCARH, MK18(320), M249, M24OG, M136 / GUST",\
"I MX, Stoner, Negev, RPG32 / Titan",\
"O Katiba, Zafir, Lynx, RPG32 / Titan",\
"I Kar98K, PKM, MG42, RPG26 / RPG7",\
"Unarmed"}

#define ROLE_SPECTATOR 99
#define ROLE_PL 0
#define ROLE_CLS 1
#define ROLE_SL 2
#define ROLE_TL 3
#define ROLE_AR 4
#define ROLE_AAR 5
#define ROLE_RAT 6
#define ROLE_CE 7
#define ROLE_R 8
#define ROLE_MG 9
#define ROLE_AM 10
#define ROLE_MGTL 11
#define ROLE_AT 12
#define ROLE_AAT 13
#define ROLE_P 14
#define ROLE_CR 15
#define ROLE_MK 16

#define UNIT_SPECTATOR "VirtualMan_F"

#define UNIT_OPFOR_PL "O_officer_F"
#define UNIT_OPFOR_CLS "O_medic_F"
#define UNIT_OPFOR_SL "O_Soldier_SL_F"
#define UNIT_OPFOR_TL "O_Soldier_TL_F"
#define UNIT_OPFOR_AR "O_Soldier_AR_F"
#define UNIT_OPFOR_AAR "O_Soldier_A_F"
#define UNIT_OPFOR_RAT "O_Soldier_LAT_F"
#define UNIT_OPFOR_CE "O_soldier_exp_F"
#define UNIT_OPFOR_R "O_Soldier_F"
#define UNIT_OPFOR_MG "O_HeavyGunner_F"
#define UNIT_OPFOR_AM "O_Soldier_unarmed_F"
#define UNIT_OPFOR_MGTL "O_soldier_PG_F"
#define UNIT_OPFOR_AT "O_Soldier_AT_F"
#define UNIT_OPFOR_AAT "O_Soldier_AAT_F"
#define UNIT_OPFOR_P "O_pilot_F"
#define UNIT_OPFOR_CR "O_crew_f"
#define UNIT_OPFOR_MK "O_soldier_M_F"

#define UNIT_BLUFOR_PL "B_officer_F"
#define UNIT_BLUFOR_CLS "B_medic_F"
#define UNIT_BLUFOR_SL "B_Soldier_SL_F"
#define UNIT_BLUFOR_TL "B_Soldier_TL_F"
#define UNIT_BLUFOR_AR "B_soldier_AR_F"
#define UNIT_BLUFOR_AAR "B_soldier_AAR_F"
#define UNIT_BLUFOR_RAT "B_soldier_LAT_F"
#define UNIT_BLUFOR_CE "B_soldier_exp_F"
#define UNIT_BLUFOR_R "B_Soldier_F"
#define UNIT_BLUFOR_MG "B_HeavyGunner_F"
#define UNIT_BLUFOR_AM "B_Soldier_unarmed_F"
#define UNIT_BLUFOR_MGTL "B_soldier_PG_F"
#define UNIT_BLUFOR_AT "B_Soldier_AT_F"
#define UNIT_BLUFOR_AAT "B_Soldier_AAT_F"
#define UNIT_BLUFOR_P "B_pilot_F"
#define UNIT_BLUFOR_CR "B_crew_F"
#define UNIT_BLUFOR_MK "B_soldier_M_F"

#define UNIT_INDFOR_PL "I_officer_F"
#define UNIT_INDFOR_CLS "I_medic_F"
#define UNIT_INDFOR_SL "I_Soldier_SL_F"
#define UNIT_INDFOR_TL "I_Soldier_TL_F"
#define UNIT_INDFOR_AR "I_Soldier_AR_F"
#define UNIT_INDFOR_AAR "I_Soldier_AAR_F"
#define UNIT_INDFOR_RAT "I_Soldier_LAT_F"
#define UNIT_INDFOR_CE "I_engineer_F"
#define UNIT_INDFOR_R "I_soldier_F"
#define UNIT_INDFOR_MG "I_support_MG_F"
#define UNIT_INDFOR_AM "I_Soldier_A_F"
#define UNIT_INDFOR_MGTL "I_Soldier_lite_F"
#define UNIT_INDFOR_AT "I_Soldier_AT_F"
#define UNIT_INDFOR_AAT "I_Soldier_AAT_F"
#define UNIT_INDFOR_P "I_pilot_F"
#define UNIT_INDFOR_CR "I_crew_F"
#define UNIT_INDFOR_MK "I_Soldier_M_F"

#define UNIT_CIV_R "C_man_1_1_F"
